package WildDexPrincipal;



import WildDexPrincipal.Mapa;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Shary
 */
public class Start extends javax.swing.JFrame implements Runnable{
    boolean oneclick=true;
    Image img;
    Graphics g;
    Image[] yee=new Image[3];
    Thread t=new Thread(this);
    int x=0, y=60;
    Boolean flag=true, up=false, down=true;
    Mapa m;
    

    

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        cargarImagenes();
        t.start();
        this.setLocationRelativeTo(null);
      //  this.setResizable(false);
        this.setTitle("WildDex");
        this.setIconImage( Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/logo.png")) );
        
    }
    
    public void cargarImagenes(){
        img=(new ImageIcon(getClass().getResource("/Recursos/WildDexBackground.png"))).getImage();
        yee[0]=img;
        img=(new ImageIcon(getClass().getResource("/Recursos/WildDexLogo.png"))).getImage();
        yee[1]=img;
        img=(new ImageIcon(getClass().getResource("/Recursos/StartButton.png"))).getImage();
        yee[2]=img;
        
    }
    
    public void run(){
        try{
            g=jPanel1.getGraphics();
            g.drawImage(yee[0], 0, 0, null);
            g=jPanel2.getGraphics();
            while(flag){
                for(;y<85;y++){
                    t.sleep(50);
                    paint(g);
                }
                for(;y>50;y--){
                    t.sleep(50);
                    paint(g);
                }
            }
//            while(flag){
//                if((y>=60 && y<85) && down==true){
//                    paint(g);
//                    t.sleep(100);
//                    y++;
//                    down=false;
//                    System.out.println("Y: "+y);
//                }
//                if(y==85 || up==true){
//                    paint(g);
//                    y--;
//                    t.sleep(100);
//                    down=true;
//                }
//            }
        }catch(InterruptedException ex){}
        
    }
    
    public void dibujar(Graphics pantalla){
        pantalla.drawImage(yee[0], 0, 0, null);
        pantalla.drawImage(yee[1], 0, y, null);
        pantalla.drawImage(yee[2], 35, 364, null);

    }
    
    public void paint(Graphics g) {
        Image buffer = jPanel2.createImage(jPanel2.getWidth(), jPanel2.getHeight());
        Graphics pantalla = buffer.getGraphics();
        update(pantalla);
        g.drawImage(buffer, 0, 0, jPanel2.getWidth(), jPanel2.getHeight(), jPanel2);
    }

    public void update(Graphics pantalla) {
        dibujar(pantalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 700));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 450));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

      if(evt.getY()>398 && evt.getY()<470 && evt.getX()>36 && evt.getX()<354)
        //  System.out.println("Yee");
          if(oneclick){
              oneclick=false;
       m=new Mapa();
       flag=false; 
       this.setVisible(false);
       
          }
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
