/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cardenalito;

import Mapas.BancoMapas;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.TextArea;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import WildDexPrincipal.Mapa;
import java.awt.Toolkit;

/**
 *
 * @author Shary
 */
public class InfoCardenal extends javax.swing.JFrame {
    Image img,IconBack,IconPlay,IconWorld,IconGallery;
    //Image hola,;
    Graphics g;
    Graphics x;
    int constanteX=0,sprite=2;
    boolean oneclick=true;
    BancoMapas bm;
        Image arreglo[];
    ///////////// MÉTODOS PARA AUDIOS
        URL url=InfoCardenal.class.getResource("CardenalitoGG.wav");
        AudioClip clip=Applet.newAudioClip(url);
    /**
     * Creates new form Info
     */
    public InfoCardenal() {
        
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("WildDex");
        this.setIconImage( Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/logo.png")) );
        super.setSize(407,725);
    }
    
    
      @Override
        public void paint(Graphics g) {
            update(g);
            repaint();
             }
 
        @Override
        public void update(Graphics g){        
                    g=jPanel1.getGraphics();
                 Image buffer = createImage(getWidth(), getHeight());
                       Graphics2D g2d = (Graphics2D) buffer.getGraphics();
        
        img=(new ImageIcon(getClass().getResource("/Recursos/Sky.png"))).getImage();
        g2d.drawImage(img, 0, 0, null);
       // hola=(new ImageIcon(getClass().getResource("/Images/prueba.png"))).getImage();
        //x.drawImage(hola, 0, 0, null);
        g2d.drawImage((new ImageIcon(getClass().getResource("/Recursos/ButtonsReturn.png"))).getImage(), 15, 15, null);
        g2d.drawImage((new ImageIcon(getClass().getResource("/Recursos/ButtonsSound.png"))).getImage(), 97, 350, null);
        g2d.drawImage((new ImageIcon(getClass().getResource("/Recursos/ButtonsWorld.png"))).getImage(), 177, 350, null);
        g2d.drawImage((new ImageIcon(getClass().getResource("/Recursos/ButtonsGallery.png"))).getImage(), 257, 350, null);
    
        g2d.drawImage((new ImageIcon(getClass().getResource("/AnimalesImages/Cardenal/CardenalArt01.png"))).getImage(), 50, 50, null);
        g2d.drawImage((new ImageIcon(getClass().getResource("/AnimalesImages/Cardenal/CardenalitoDatos.png"))).getImage(), constanteX, 0, null);
        
        g2d.drawImage((new ImageIcon(getClass().getResource("/Recursos/ButtonsLeft.png"))).getImage(), 12, 640, null);
        g2d.drawImage((new ImageIcon(getClass().getResource("/Recursos/ButtonsRight.png"))).getImage(), 338, 640, null);
        g2d.drawImage( (new ImageIcon(getClass().getResource("/Recursos/NamesFlycatcher.png"))).getImage() , 55, 20, null);
    
    
    g.drawImage(buffer, 0, 0, null);
        
      
            try {
                Thread.sleep(50);
            } catch (InterruptedException ex) {}
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        adios = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 700));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setPreferredSize(new java.awt.Dimension(30, 290));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel7.setPreferredSize(new java.awt.Dimension(30, 290));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.LINE_START);

        adios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));

        javax.swing.GroupLayout adiosLayout = new javax.swing.GroupLayout(adios);
        adios.setLayout(adiosLayout);
        adiosLayout.setHorizontalGroup(
            adiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        adiosLayout.setVerticalGroup(
            adiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        jPanel2.add(adios, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel8.setMinimumSize(new java.awt.Dimension(365, 100));
        jPanel8.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanel3.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(400, 10));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setPreferredSize(new java.awt.Dimension(400, 10));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        jPanel15.setPreferredSize(new java.awt.Dimension(30, 190));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel16.setPreferredSize(new java.awt.Dimension(30, 190));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel16, java.awt.BorderLayout.LINE_START);

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
   
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

       
       if(evt.getY()>23 && evt.getY()<63 && evt.getX()>23 && evt.getX()<63){
         //  System.out.println("Sali");
         if(oneclick){
                oneclick=false;
           Mapa m=new Mapa();
           this.setVisible(false);
         }
       }
       
       if(evt.getY()>360 && evt.getY()<400 && evt.getX()> 102 && evt.getX()<151){
                        clip.play();
       }
       
       if(evt.getY()>360 && evt.getY()<400 && evt.getX()> 184 && evt.getX()<228){
         //  System.out.println("Mundo");
         if(oneclick){
                oneclick=false;
          MapaCardenal mB=new MapaCardenal();
          this.setVisible(false);
         }
       }
       
       if(evt.getY()>360 && evt.getY()<400 && evt.getX()> 264 && evt.getX()<303){
           //System.out.println("Galeria");
           if(oneclick){
                oneclick=false;
           GalleriaCardenal gC=new GalleriaCardenal();
           gC.setVisible(true);
           this.setVisible(false);
           }
       }
       
       if(evt.getY()>640 && evt.getY()<690 && evt.getX()> 12 && evt.getX()<63){
           if(constanteX<0)constanteX+=400;
      //     dibujarComponentes();
                   
       }
       
       if(evt.getY()>640 && evt.getY()<690 && evt.getX()> 349 && evt.getX()<389){
           if(constanteX>-800)constanteX-=400;
         //  dibujarComponentes();
          
       }
       
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoCardenal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoCardenal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoCardenal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoCardenal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoCardenal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
